#!/bin/bash

# Rotate screen 90 degrees right
xrandr --output DSI1 --rotate inverted
# Rotate touchscreen input
xinput set-prop 'pointer:Goodix Capacitive TouchScreen' 'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1
